# Generated by Django 4.1.2 on 2024-05-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.CharField(max_length=100),
        ),
    ]
